### PR TITLE
Create sko1-skj.json

### PR DESCRIPTION
**Pull request by BorowskaNatalia**

### CODE REVIEW

**Review by JapaneseZgredek — COMMENTED** [review]
Where is the rest of the answers?

**Comment by bibixx** [comment]
@JapaneseZgredek @BorowskaNatalia just so you guys know, this isn't the best solution yet (just implemented editing yesterday 😅) and it gets quite confusing if there are no overrides (in regards to mykhi) for a subject.

I'll try to sit down to all of the SKJ PRs today, combine them into one and merge at once

**Comment by bibixx** [comment]
Hey @BorowskaNatalia it seems like you didn't copy the whole JSON from the contribution guide on [zdaj.se](https://pjatk.zdaj.se/). To copy everything, you can click on this button
CleanShot 2023-02-07 at 19 21 13@2x

**Comment by JapaneseZgredek** [comment]
> @JapaneseZgredek @BorowskaNatalia just so you guys know, this isn't the best solution yet (just implemented editing yesterday 😅) and it gets quite confusing if there are no overrides (in regards to mykhi) for a subject.
> 
> I'll try to sit down to all of the SKJ PRs today, combine them into one and merge at once

That would be lovely, I think that worth considering is the option to provide some article or any info, into the comment of PR, that proofs, that our change is correct. We have to remember it is PJATK, and there will be always some guy "you are market competition for me", that will try to change all answers to wrong ones

**Comment by bibixx** [comment]
As you can see [commit for adding editing](https://github.com/bibixx/zdaj-se-pjatk/commit/db9af015160d97a6ecaea50af88bed08429b9c09) was merged today at 1:10 am so I didn't have time for everything 😉
But yes, I planned on adding some kind of a template for PR

**Comment by bibixx** [comment]
@BorowskaNatalia If you want to have this question changed, feel free to reopen this PR after you have corrected the answer

**Pull request closed without merging**
