### PR TITLE
Correction to tak_eng question

### PR DESCRIPTION
**Pull request by Volodymyr-Yeikovych**
In the generator the correct answer was that RAM is realised via electrodynamic technology. Which is not correct. Changed to magnetic technology.

### CODE REVIEW

**Comment by bibixx** [comment]
Hey @Volodymyr-Yeikovych it seems like you didn't copy the whole JSON from the contribution guide on [zdaj.se](https://pjatk.zdaj.se/). To copy everything, you can click on this button
CleanShot 2023-02-07 at 19 21 13@2x

**Comment by Volodymyr-Yeikovych** [comment]
True, thx ill fix it.

**Comment by bibixx** [comment]
@Volodymyr-Yeikovych this doesn't seem right for me. Could you give any source for this change?

**Comment by Volodymyr-Yeikovych** [comment]
Ok one second.

**Comment by Volodymyr-Yeikovych** [comment]
It's indeed wrong. My bad) I missresearched

**Pull request closed without merging**
